### ISSUE TITLE
Mailman3 core service cannot be started

### ISSUE THREAD

**Issue by iomarmochtar** [iomarmochtar/mailman3_ei#1]
Got some report as below

> /etc/init.d/mailman3: line 69: /opt/mailman3/conda/bin/mailman: No such file or directory
> /etc/init.d/mailman3: line 72: /opt/mailman3/conda/bin/mailman: No such file or directory

**Comment by iomarmochtar** [comment]
After checking in command log file there was some error while installing mailman3 core dependencies as in file mailman3_core_requirements.txt, some library has removed mentioned version in it.

because it's not directly a dependencies for mailman. so after remove them the installer running well.

**Comment by iomarmochtar** [comment]
For those who has face or reported the same issue, run this command for reinstalling mailman3 core (and it's dependencies).

`/opt/mailman3/conda/bin/pip install -r /opt/mailman3/misc/mailman3_core_requirements.txt`

**Comment by infracritical** [comment]
Have encountered this error message:

Found existing installation: certifi 2018.4.16
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Thoughts on how to fix this?
