### ISSUE TITLE
How to run mailman commands from console?

### ISSUE THREAD

**Issue by alexmtv** [iomarmochtar/mailman3_ei#2]
Hello!
Setup was fine, without any errors.

I wanna run mailman info (and other command-line tools), but got this:

[root@mailman3t ~]# mailman3 info
-bash: mailman3: command not found
[root@mailman3t ~]# mailman info
-bash: mailman: command not found

[root@mailman3t ~]# systemctl status mailman3
● mailman3.service - SYSV: The GNU Mailing List manager.
   Loaded: loaded (/etc/rc.d/init.d/mailman3; bad; vendor preset: disabled)
   Active: active (exited) since Fri 2018-03-02 13:41:41
     Docs: man:systemd-sysv-generator(8)
  Process: 10958 ExecStart=/etc/rc.d/init.d/mailman3 start (code=exited, status=0/SUCCESS)

**Comment by alexmtv** [comment]
[root@mailman3t ~]# python
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
[root@mailman3t ~]# python /opt/mailman3/conda/bin/mailman
Traceback (most recent call last):
  File "/opt/mailman3/conda/bin/mailman", line 7, in <module>
    from mailman.bin.mailman import main
ImportError: No module named mailman.bin.mailman

**Comment by iomarmochtar** [comment]
Hello @alexmtv ,

You may just run directly to mailman script 
`[root@mailman3t ~]# /opt/mailman3/conda/bin/mailman info`

**Comment by alexmtv** [comment]
@iomarmochtar , thanks for your reply
It works, but it output is incorrect

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19)
[GCC 7.2.0]
config file: None
db url: sqlite:////root/var/data/mailman.db
devmode: DISABLED
REST root url: http://localhost:8001/3.1/
REST credentials: restadmin:restpass

Also, after this, mailman create var directory under root and new db in data folder. 
How about adding "Filesystem Path pointed to by MAILMAN_CONFIG_FILE environment variable" in your script? 
http://docs.mailman3.org/en/latest/config-core.html#configuring-filesystem-paths

**Comment by iomarmochtar** [comment]
actually you must change working directory to **/opt/mailman3** before you run mailman command.

but for you or maybe others not confuse about it so i made wrapper in path **/opt/mailman3/bin/mailman**

Please pull the new changes to apply it and thanks for the suggestion.
