### ISSUE TITLE
Mailman (web) now only requires Python 3

### ISSUE THREAD

**Issue by alexmtv** [iomarmochtar/mailman3_ei#3]
Hello again!
From lists:
https://lists.mailman3.org/archives/list/mailman-users@mailman3.org/thread/47PG3ATNDHM5EYA5HSA5DZCYSFVCPPFY/#47PG3ATNDHM5EYA5HSA5DZCYSFVCPPFY

@iomarmochtar If I decide to update your script, where should I start? Move the list of Python 2 packages to Python 3? Remove all references to python 2 binary?

Thanks in advance!

**Comment by iomarmochtar** [comment]
thanks for the information @alexmtv ,

let me update the script, because previously django-mailman3 can be run only in python2.

**Comment by iomarmochtar** [comment]
You can try following command to upgrade all packages in environment mailman3_ext from python version 2.7 to 3.6 (while i'm updating/push new changes to this repo)

Assuming you are using centos version 7.

- Stop mailman3 webui and remove it.
```
service mailman3_webui stop
rm -f /etc/init.d/mailman3_webui
```

- Remove existing virtual env for mailman3_ext
```
/opt/mailman3/conda/bin/conda remove --name mailman3_ext --all
```
- Reinstall with python 3
```
/opt/mailman3/conda/bin/conda create --name mailman3_ext python=3 -y 
```

- Install all dependencies
```
/opt/mailman3/conda/envs/mailman3_ext/bin/pip install Whoosh==2.7.4 libsass==0.14.5 postorius==1.2.0a1 hyperkitty==1.2.0a1 Django==1.11 django-mailman3==1.2.0a2 django-haystack==2.8.1 mailmanclient==3.2.0b1 waitress==1.1.0
```

- Apply any new migration from used django apps.
```
/opt/mailman3/conda/envs/mailman3_ext/bin/python /opt/mailman3/webui/manage.py migrate
```

- Install supervisord from repository
```
yum install supervisord
```

- Move all service script to system's supervisord
```
cp /opt/mailman3/etc/supervisor/services/*.ini /etc/supervisord.d/
```
- Start the service which currently handled by system's supervisord
```
systemctl start supervisord
```
