### ISSUE TITLE
Your easy install isn't complete...

### ISSUE THREAD

**Issue by infracritical** [iomarmochtar/mailman3_ei#4]
I've followed your mailman3_ei instructions to the letter.

There is no webui service (checked /etc/init.d; only mailman3, no mailman3_webui).
There is no nginx service.
There is no postorius service.

Are you making assumptions that whomever is reading your instructions knows what they're doing?  Are there any preliminary steps that must be followed BEFORE applying your instructions?

Please advise.  Thanks.

-rad

**Comment by iomarmochtar** [comment]
Please check this https://github.com/iomarmochtar/mailman3_ei/issues/5 , because it's the same issue i will close this one.
